server:
  port: 8001
  servlet:
    context-path: /
spring:
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/quiz?characterEncoding=utf8&useSSL=false&autoReconnection=true
      username: hope
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
  api-docs:
    path: /openapi/api-docs
  swagger-ui:
    path: /openapi/swagger-ui.html